# Generated by Django 4.1.1 on 2022-12-10 19:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisements', '0004_advertisement_favor_users_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='favor_users',
            field=models.ManyToManyField(related_name='favorite_advs', to=settings.AUTH_USER_MODEL),
        ),
    ]
