# Generated by Django 4.1.1 on 2022-12-19 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisements', '0005_alter_advertisement_favor_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='favor_users',
            field=models.ManyToManyField(blank=True, related_name='favorite_advs', to=settings.AUTH_USER_MODEL),
        ),
    ]
