# Generated by Django 4.1 on 2022-08-17 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_scopes_alter_article_options_tags_scopes_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(verbose_name='Основной')),
                ('article', models.ManyToManyField(related_name='scopes', through='articles.Tags', to='articles.article')),
            ],
        ),
        migrations.AlterField(
            model_name='tags',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='articles.scope'),
        ),
        migrations.DeleteModel(
            name='Scopes',
        ),
    ]
