# Generated by Django 4.1 on 2022-08-18 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_rename_tags_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='is_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_main', to='articles.article'),
        ),
    ]
