# Generated by Django 4.1 on 2022-08-18 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_scope_is_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scopes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='tag',
            name='scope',
        ),
        migrations.DeleteModel(
            name='Scope',
        ),
        migrations.AddField(
            model_name='scopes',
            name='article',
            field=models.ManyToManyField(related_name='scopes', through='articles.Tag', to='articles.article'),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_main', to='articles.scopes'),
        ),
    ]
