# Generated by Django 4.1 on 2022-08-18 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_scopes_remove_tag_scope_delete_scope_scopes_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_mains',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_main', to='articles.scopes', verbose_name='Багапш'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_main',
            field=models.BooleanField(null=True, verbose_name='Основной'),
        ),
    ]
