# Generated by Django 4.1 on 2022-08-18 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_tag_is_mains_alter_tag_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='is_mains',
        ),
        migrations.AddField(
            model_name='tag',
            name='scope',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_main', to='articles.scopes'),
        ),
    ]
