# Generated by Django 4.1 on 2022-08-18 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_remove_tag_is_mains_tag_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='scope',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_main', to='articles.scopes'),
        ),
    ]
