# Generated by Django 4.1 on 2022-09-02 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_tag_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(null=True, verbose_name='Основной')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope', to='articles.article')),
            ],
        ),
        migrations.RemoveField(
            model_name='tag',
            name='is_main',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='article',
        ),
        migrations.DeleteModel(
            name='Scopes',
        ),
        migrations.AddField(
            model_name='scope',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scope', to='articles.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='article',
            field=models.ManyToManyField(related_name='tag', through='articles.Scope', to='articles.article'),
        ),
    ]
