# Generated by Django 4.1 on 2022-08-09 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_student_teacher_pairs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='teacher',
            new_name='teachers',
        ),
        migrations.DeleteModel(
            name='Pairs',
        ),
    ]
