# Generated by Django 4.1 on 2022-08-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_rename_teacher_student_teachers_delete_pairs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(related_name='students', to='school.teacher'),
        ),
    ]
