# Generated by Django 4.1 on 2022-09-02 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('temperature', models.DecimalField(decimal_places=0, max_digits=1, verbose_name='Температура')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement', to='measurement.sensor')),
            ],
        ),
    ]
