# Generated by Django 4.1 on 2022-09-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_alter_measurement_date_alter_measurement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='temperature',
            field=models.PositiveIntegerField(verbose_name='Температура'),
        ),
    ]
