# Generated by Django 4.1 on 2022-08-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('slug', models.SlugField(max_length=80, verbose_name='URL')),
                ('price', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=150)),
                ('release_date', models.CharField(max_length=150)),
                ('lte_exists', models.CharField(max_length=150)),
            ],
        ),
    ]
